# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='multi',
            field=models.BooleanField(default=False),
        ),
    ]
