# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160911_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='textenter',
            name='include_in_raport',
            field=models.BooleanField(default=False),
        ),
    ]
