# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_textenter_include_in_raport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailenter',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='textenter',
            name='poll',
        ),
        migrations.AddField(
            model_name='visitor',
            name='textentries',
            field=models.ManyToManyField(to='polls.TextEnter'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='textenter',
            name='label',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='textenter',
            name='text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='textpoll',
            name='question',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='EmailEnter',
        ),
    ]
