# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160912_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='textenter',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.TextPoll'),
            preserve_default=False,
        ),
    ]
