# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_textenter_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='countries',
            field=models.BooleanField(default=False),
        ),
    ]
