# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_poll_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='multi',
            new_name='enter_text',
        ),
        migrations.AddField(
            model_name='poll',
            name='pick_multiple_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poll',
            name='pick_one_option',
            field=models.BooleanField(default=True),
        ),
    ]
