# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160913_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='enter_text',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='pick_multiple_options',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='pick_one_option',
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('multi', 'pick multiple options'), ('one', 'pick one option'), ('countries', 'pick a country from a list'), ('text', 'type text')], default='multi', max_length=30),
        ),
    ]
