# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_poll_first_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['the_order'], 'verbose_name_plural': 'Polls'},
        ),
        migrations.AddField(
            model_name='poll',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('multi', 'pick multiple options'), ('one', 'pick one option'), ('countries', 'pick a country from the list'), ('text', 'type text'), ('email_now', 'email - save and send at Submit'), ('email', 'email - just save'), ('first_name', 'enter first name')], default='multi', max_length=30),
        ),
    ]
