# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 17:44
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20160918_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='survey',
        ),
        migrations.AddField(
            model_name='poll',
            name='survey',
            field=adminsortable.fields.SortableForeignKey(blank=True, default=9, on_delete=django.db.models.deletion.CASCADE, to='polls.Survey'),
            preserve_default=False,
        ),
    ]
