# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20160919_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charchoice',
            options={'ordering': ['choice_order'], 'verbose_name_plural': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['poll_order'], 'verbose_name_plural': 'Polls'},
        ),
        migrations.RenameField(
            model_name='charchoice',
            old_name='the_order',
            new_name='choice_order',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='the_order',
            new_name='poll_order',
        ),
    ]
