# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20160919_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name_plural': 'Surveys'},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='the_order',
        ),
    ]
