# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20160919_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charchoice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
    ]
