# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 10:42
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20160920_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['the_order'], 'verbose_name_plural': 'Surveys'},
        ),
        migrations.AlterField(
            model_name='charchoice',
            name='poll',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
    ]
