# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20160920_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('numeric_value', models.IntegerField()),
                ('attr_type', models.CharField(choices=[('summarize', 'summarize'), ('count', 'count'), ('average', 'average')], max_length=30)),
                ('polls', models.ManyToManyField(to='polls.Poll')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Survey')),
            ],
        ),
    ]
