# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20160921_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyattribute',
            name='numeric_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
