# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20160921_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='include_in_details',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='include_raport',
        ),
        migrations.AddField(
            model_name='poll',
            name='include_in_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='include_raport',
            field=models.BooleanField(default=True),
        ),
    ]
