# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20160922_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='ghost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='hide_ghost',
            field=models.BooleanField(default=True),
        ),
    ]
