# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20160922_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyattribute',
            name='numeric_value',
        ),
        migrations.AlterField(
            model_name='surveyattribute',
            name='attr_type',
            field=models.CharField(choices=[('summarize', 'summarize'), ('count', 'count answers'), ('average', 'calc average')], max_length=30),
        ),
        migrations.AlterField(
            model_name='surveyattribute',
            name='dicti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Dicty', verbose_name='values'),
        ),
    ]
