# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_auto_20160922_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='include_raport',
            new_name='include_in_raport',
        ),
        migrations.AlterField(
            model_name='surveyattribute',
            name='attr_type',
            field=models.CharField(choices=[('summarize', 'summarize'), ('count', 'count answers'), ('average', 'calc average')], max_length=30, verbose_name='action'),
        ),
    ]
