# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20160922_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_newsletter', to='polls.Email'),
        ),
        migrations.AddField(
            model_name='survey',
            name='welcome_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_welcome', to='polls.Email'),
        ),
    ]
