# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_auto_20160923_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='text',
            new_name='body',
        ),
    ]
