# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_auto_20160923_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
