# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_visitor_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattribute',
            name='include_in_raport',
            field=models.BooleanField(default=True),
        ),
    ]
