# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_surveyattribute_include_in_raport'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='publish_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
