# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_survey_publish_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('multi', 'pick multiple options'), ('one', 'pick one option'), ('countries', 'pick a country from the list'), ('text', 'type text'), ('email_now', 'email - save and send at Submit'), ('email', 'email - just save'), ('first_name', 'enter first name'), ('phone', 'telephone number')], default='multi', max_length=30),
        ),
    ]
