# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_auto_20160928_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='group',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
