# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_poll_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='group',
        ),
        migrations.AddField(
            model_name='poll',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Group'),
        ),
    ]
