# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_auto_20161002_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='groups',
        ),
        migrations.AddField(
            model_name='poll',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Group'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='collected_data',
            field=models.ManyToManyField(to='polls.Dicty'),
        ),
    ]
