# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_auto_20161003_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicty',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='collected_data',
        ),
        migrations.AddField(
            model_name='visitor',
            name='collected_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Dicty'),
        ),
    ]
