# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_auto_20161003_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='keyval',
            name='value',
            field=models.CharField(default=0, max_length=1500),
        ),
        migrations.AddField(
            model_name='charchoice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.ChoiceGroup'),
        ),
    ]
