# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_auto_20161004_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='key',
            field=models.CharField(max_length=500),
        ),
    ]
