# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_auto_20161004_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['poll_order']},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='active',
        ),
    ]
