# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_auto_20161012_1816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='PollGroup',
        ),
        migrations.AlterModelOptions(
            name='e_mail',
            options={'verbose_name': 'E-mail'},
        ),
    ]
