# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0055_auto_20161013_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='E_mail',
            new_name='Elmail',
        ),
    ]
