# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0057_auto_20161013_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='welcome_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_welcome', to='polls.Elmail'),
        ),
    ]
