# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0058_auto_20161018_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
