# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0059_survey_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyPreferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, db_index=True, default=None, max_length=150, null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Survey')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'survey preferences',
                'verbose_name': 'survey preference',
            },
        ),
        migrations.AlterUniqueTogether(
            name='surveypreferencemodel',
            unique_together=set([('instance', 'section', 'name')]),
        ),
    ]
