# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0061_auto_20161023_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyPreferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_size', models.IntegerField(default=150)),
                ('description_size', models.IntegerField(default=100)),
                ('question_size', models.IntegerField(default=100)),
                ('choice_size', models.IntegerField(default=80)),
                ('left_margin', models.IntegerField(default=100)),
                ('indentation', models.IntegerField(default=50)),
                ('background_color', models.CharField(default='white', max_length=40)),
                ('header_color', models.CharField(default='black', max_length=40)),
                ('description_color', models.CharField(default='black', max_length=40)),
                ('question_color', models.CharField(default='black', max_length=40)),
                ('choice_color', models.CharField(default='black', max_length=40)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Survey')),
            ],
            options={
                'verbose_name_plural': 'survey preferences',
                'verbose_name': 'survey preference',
            },
        ),
    ]
