# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0062_surveypreferencemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveypreferencemodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='surveypreferencemodel',
            name='survey',
        ),
        migrations.AddField(
            model_name='surveypreferencemodel',
            name='survey_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Survey'),
            preserve_default=False,
        ),
    ]
