# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0063_auto_20161023_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveypreferencemodel',
            name='survey_ptr',
        ),
        migrations.AddField(
            model_name='survey',
            name='background_color',
            field=models.CharField(default='white', max_length=40),
        ),
        migrations.AddField(
            model_name='survey',
            name='choice_color',
            field=models.CharField(default='black', max_length=40),
        ),
        migrations.AddField(
            model_name='survey',
            name='choice_size',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_color',
            field=models.CharField(default='black', max_length=40),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='header_color',
            field=models.CharField(default='black', max_length=40),
        ),
        migrations.AddField(
            model_name='survey',
            name='header_size',
            field=models.IntegerField(default=150),
        ),
        migrations.AddField(
            model_name='survey',
            name='indentation',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='survey',
            name='left_margin',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_color',
            field=models.CharField(default='black', max_length=40),
        ),
        migrations.AddField(
            model_name='survey',
            name='question_size',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='SurveyPreferenceModel',
        ),
    ]
