# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0064_auto_20161023_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='indentation',
        ),
        migrations.AddField(
            model_name='survey',
            name='choice_indent',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='font',
            field=models.CharField(choices=[('Times', "'Times New Roman', Times, serif"), ('Monospace', "'Courier New', Courier, monospace"), ('Sans', 'Arial, Helvetica, sans-serif'), ('Century Gothic', "'Century Gothic', CenturyGothic, AppleGothic, sans-serif;"), ('Futura', "Futura, 'Trebuchet MS', Arial, sans-serif"), ('Garamond', "Garamond, Baskerville, 'Baskerville Old Face', 'Hoefler Text', 'Times New Roman', serif"), ('Rockwel', "Rockwell, 'Courier Bold', Courier, Georgia, Times, 'Times New Roman', serif")], default='Sans', max_length=30),
        ),
        migrations.AddField(
            model_name='survey',
            name='nested_indent',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='left_margin',
            field=models.IntegerField(default=10),
        ),
    ]
