# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0065_auto_20161023_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='top_margin',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='survey',
            name='choice_indent',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='survey',
            name='choice_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description_size',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='survey',
            name='font',
            field=models.CharField(choices=[('Times', "'Times New Roman', Times, serif"), ('Monospace', "'Courier New', Courier, monospace"), ('Sans', 'Arial, Helvetica, sans-serif'), ('Century Gothic', "'Century Gothic', CenturyGothic, AppleGothic, sans-serif;"), ('Futura', "Futura, 'Trebuchet MS', Arial, sans-serif"), ('Garamond', "Garamond, Baskerville, 'Baskerville Old Face', 'Hoefler Text', 'Times New Roman', serif"), ('Rockwel', "Rockwell, 'Courier Bold', Courier, Georgia, Times, 'Times New Roman', serif")], default='Sans', max_length=30, verbose_name='Font Family'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='header_color',
            field=models.CharField(default='black', max_length=40, verbose_name='Title Color'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='header_size',
            field=models.IntegerField(default=180, verbose_name='Title Size'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='nested_indent',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_size',
            field=models.IntegerField(default=130),
        ),
    ]
