# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 09:23
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0066_auto_20161023_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('logo', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
