# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 10:01
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0068_auto_20161024_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('logo', '530x360', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
