# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 11:38
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0071_auto_20161024_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='logo',
            field=image_cropping.fields.ImageCropField(upload_to=''),
        ),
    ]
