# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0075_survey_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='notify',
            field=models.BooleanField(default=False, verbose_name='Receive email notification for every submit'),
        ),
    ]
